### ISSUE TITLE
Sparklines not working in Python 3

### ISSUE THREAD

**Issue by snives** [iiSeymour/sparkline-nb#2]
This sparkline function is pretty cool, it was exactly what I was looking for.  I'm running in a Python3 environment however and it appears as though it no longer works.  e.g. cStringIO is deprecated in Python 3.  I think the fixer.io API has changed also but I didn't touch that part.

I've forked the project and made the fixes.  Let me know if you will accept a pull request.  thanks!

**Comment by iiSeymour** [comment]
Thanks @snives
